language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm test
before_install:
- chmod ugo+x commit-build.sh
after_success:
- npm run coverage
- npm run build
- "./commit-build.sh"
deploy:
  provider: releases
  api_key:
    secure: uOYWY65eLJnfY0Iq9kVxtCK/40Ha3md8xtGBvWN8+SJNpNGx585gIuX1Brz6gfIgUQK25n6QDmcX+OGGTSQdo6AJkCna3WqvRaPGf10MRSZDNkB70OCz02S7+G/hy6iC8lArsmqwGLvjym+tjayEX2Z6KgTVMtvcTOUhqWE9affyAG1KQSy1nQEZjNXmALrBNRWF1SYT8XfPo7XLyFOAeIudIElP92Kbw6yOnvDvuU2s7L6VudlKHH84MYOrnCZq6oImrzEypmhAlZyJr7VRzBYUp6WvY6AqGluPUdQ+wN3ZhwxvSdzxpyJBBDrEIfMfOebcDkxxAoiBUKbsoFCSd8TvZfiFULGDnJzs2tEzf1+FiBmtW5WhKYA/jktmixjFDbnFjpCC7YqALzbzwGTtNUVbT1dFl5R5YMkae5tR+p49vySqJE4l/JybnCfXmWGuBD+4tl4ccfbKtiAbu9Agl1ayhx8/sbqasWZF3hiUOypuU+AlILmuXdYMuPC8sboJzsWd6x6YYHct2ABCVUgJhJ7icjLkrngRAJEvblEt/BdV8YwPw6EZD1Rh8eCRckCwyN+AlVrnGQ2SjHw6VwJTlJBATxA80KIZbi1YitOsiWgGy/9xcmJeauLlG4wmdamszyLv2EuucxaYQTK3eZJQooYNY8Sc3ZRvy8BVLfXYr/U=
  file: "./dist/rstore.js"
  on:
    repo: nikitadyumin/rstore
