language: node_js
env:
  global:
    - secure: ZsofdXCKEfkuUahU728sTlgnRiHJXqP+tyKjLwj4nh1BuE/toBdnOWlXtBg9vhwyWXr/drHdhQ7yfME2/N26bg4ZZXELbqXe0/kBqCqeWE6ojZpJePPAp6gCng0OikucHfL8N/BMWxCDAKXpVzzGH7k2hQbbWi/FssHwXxfG6BPsH3TyYAjy6d+j2yRiz+4A+9Ndl2NGgCt+krdENvCFVOL/nK8g8a7l2PpwnnNYG3OSKZ0iuZ9vr6u6GqHrniWYnDp+OlUC65V4G0u3rIFbMRQ/CEPwq3qPTIDaUX+W/tuxAYbW1vkWXDnvCziGOM9T7NXkIXCW6sQZ2X+YHuAkD2CH7q0uR7FfeMai9mj+OcIePvBedTonEvKQM9FNj8l5CRndI8pR4HrSlKJdI4Tsc/pCNZKzObOCoVwW0Bv8zP3F22QmOmBaaUWkm58SLcYEeUf3k6nIjQwfRbhTNAuPlq14yMWwpwu0z9lbbjnmeyTXQn2sCOFJJa3YR+TuHe4+O1N4sfQGQ6Wi9awkOxznOHvW6UQ6EWNgHEgI8nb2UHLB2/4t+iUKwwHyCxQ9A7m9D1XTlbWgYVz+hgCDuhWoKV68yKht21aw9As9H/VQKzGPozbG9reQi/JFrJkLaI0N/P9DuEL5STRWBaJd48BI+nkO2QBuxLIoRFMJG5iQBNA=

node_js:
  - 6
cache:
  directories:
  - node_modules
script:
  - npm test

before_install:
  - chmod ugo+x commit-build.sh

after_success:
  - npm run coverage
  - npm run build
  - ./commit-build.sh