language: node_js
node_js:
  - 6
cache:
  directories:
  - node_modules
script:
  - npm test

before_install:
  - chmod ugo+x commit-build.sh

after_success:
  - npm run coverage
  - npm run build
  - ./commit-build.sh